# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.15.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: true
odoo_test_flavor: Both
odoo_version: 16.0
org_name: ito-invest.lu (Jerome Sonnet)
org_slug: ito-invest-lu
rebel_module_groups: []
repo_description: Main repo of Horizon project
repo_name: High School Management for Odoo
repo_slug: horizon
repo_website: https://github.com/ito-invest-lu/horizon
travis_apt_packages: []
travis_apt_sources: []

